### ISSUE TITLE
5.3.5. DomainParticipantListener Discovery Callbacks lacks info on including StatusMask::none() for not sabotaging subscribers

### ISSUE THREAD

**Issue by ma30002000** [eProsima/Fast-DDS-docs#277]
The issue described https://github.com/eProsima/Fast-DDS/issues/2106 seems to originate in improperly configuring DomainParticipantFactory::create_participant(), like described on page https://fast-dds.docs.eprosima.com/en/latest/fastdds/discovery/disc_callbacks.html . I think the example code should add the StatusMask::none() to the create_participant() code.

**Comment by JLBuenoLopez-eProsima** [comment]
Hi @ma30002000,

I have issued #280 trying to clarify this issue.

I do not think that the example you mention should be changed. That example only refers to the discovery callbacks that can be used with `DomainParticipantListener`. That specific example is not related with how the data is notified to the user or by which callback. I have tried to clarify that point in the Entity Listener section, as well as adding links to this section both in this example you mention as in the `DomainParticipantListener` section so the user is aware of what is being done and can configure the callbacks correctly for its use case. I hope it helps for further reference!
