### ISSUE TITLE
Can you provide documents compiled by Android [14045]

### ISSUE THREAD

**Issue by lxc777** [eProsima/Fast-DDS-docs#350]

**Comment by JLBuenoLopez-eProsima** [comment]
Hi @lxc777,

What do you mean? Could you provide with more information about your question? Our documentation is built using [Sphinx](https://www.sphinx-doc.org/en/master/index.html) and you can find more information in the [README](https://github.com/eProsima/Fast-DDS-docs#simulating-read-the-docs).

**Comment by lxc777** [comment]
@JLBuenoLopez-eProsima Thank you very much for your reply. I have found a solution
