### ISSUE TITLE
Wrong example to disable multicast traffic

### ISSUE THREAD

**Issue by mlanas** [eProsima/Fast-DDS-docs#520]
Is this line correct? You should add a *metatraffic* unicast locator to prevent multicast traffic, not a *user-traffic* unicast locator. Or am I understanding something wrong?

https://github.com/eProsima/Fast-DDS-docs/blob/890e3fa186737cd8d1e22c33960d71b70056d16d/docs/fastdds/transport/listening_locators.rst?plain=1#L180

**Comment by JLBuenoLopez-eProsima** [comment]
Thanks @mlanas,

You are right and this is a typo. I have issued #521 to fix it.
